import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Multimodal RAG Assistant",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </head>
      <body className={inter.className}>
        <div className="flex">
          <div className="w-64 h-screen bg-gray-800 text-white p-4">
            <h2 className="text-2xl font-semibold mb-6">Multimodal RAG</h2>
            <nav className="space-y-4">
              <Link legacyBehavior href="/collection">
                <a className="block p-2 rounded hover:bg-gray-700">Collection</a>
              </Link>
              <hr className="border-gray-600" />
              <Link legacyBehavior href="/objects">
                <a className="block p-2 rounded hover:bg-gray-700">Objects</a>
              </Link>
              <hr className="border-gray-600" />
              <Link legacyBehavior href="/search">
                <a className="block p-2 rounded hover:bg-gray-700">Search</a>
              </Link>
            </nav>
          </div>
          <div className="flex-1 p-6">{children}</div>
        </div>
      </body>
    </html>
  );
}
